SELECT
    TABLE_NAME AS tableName,
    KEY_NAME AS indexName,
    ANY_VALUE(NON_UNIQUE) AS nonUnique,
    GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) AS columns,
    ANY_VALUE(IS_VISIBLE) AS isVisible,
    ANY_VALUE(CLUSTERED) AS clustered
FROM INFORMATION_SCHEMA.TIDB_INDEXES
WHERE
    TABLE_SCHEMA = database()
GROUP BY TABLE_NAME, KEY_NAME;
