id: 10004
name: Web Framework
items:
  - spring-projects/spring-boot
  - rails/rails
  - laravel/laravel
  - symfony/symfony
  - django/django
  - pallets/flask
  - savsgio/atreugo
  - go-chi/chi
  - labstack/echo
  - valyala/fasthttp
  - gin-gonic/gin
  - gogf/gf
  - emicklei/go-restful
  - gorilla/mux
  - go-goyave/goyave
  - julienschmidt/httprouter
  - go-martini/martini
  - urfave/negroni
  - actix/actix-web
  - tokio-rs/axum
  - gotham-rs/gotham
  - rwf2/Rocket
  - thruster-rs/Thruster
  - http-rs/tide
  - seanmonstar/warp
  - salvo-rs/salvo
  - trillium-rs/trillium
  - expressjs/express
  - nestjs/nest
  - meteor/meteor
  - strapi/strapi
  - koajs/koa
  - balderdashy/sails
  - fastify/fastify
  - feathersjs/feathers
  - hapijs/hapi
  - strongloop/loopback
  - linnovate/mean
  - adonisjs/core
  - restify/node-restify
  - lukeed/polka
  - moleculerjs/moleculer
  - totaljs/framework
  - actionhero/actionhero
  - tinyhttp/tinyhttp
  - phoenixframework/phoenix
  - sinatra/sinatra
  - cakephp/cakephp
  - dotnet/aspnetcore
  - spring-projects/spring-framework
  - playframework/playframework
  - yiisoft/yii2
  - slimphp/Slim
  - bcit-ci/CodeIgniter
  - beego/beego
  - denoland/fresh
  - honojs/hono
  - refinedev/refine
  - nitrojs/nitro
  - payloadcms/payload
  - fastapi/fastapi
  - Healthlane-Technologies/Zango
