id: 10005
name: Javascript Framework
items:
  - marko-js/marko
  - MithrilJS/mithril.js
  - angular/angular
  - angular/angular.js
  - emberjs/ember.js
  - knockout/knockout
  - tastejs/todomvc
  - spine/spine
  - vuejs/vue
  - vuejs/core
  - Polymer/polymer
  - facebook/react
  - finom/seemple
  - aurelia/framework
  - optimizely/nuclear-js
  - jashkenas/backbone
  - dojo/dojo
  - jorgebucaran/hyperapp
  - riot/riot
  - Daemonite/material
  - lit/lit-element
  - aurelia/aurelia
  - sveltejs/svelte
  - neomjs/neo
  - preactjs/preact
  - hotwired/stimulus
  - alpinejs/alpine
  - solidjs/solid
  - stenciljs/core
  - jquery/jquery
  - QwikDev/qwik
  - refinedev/refine
