id: 10013
name: Game Engine
items:
  - godotengine/godot
  - turbulenz/turbulenz_engine
  - TorqueGameEngines/Torque3D
  - TorqueGameEngines/Torque2D
  - spring/spring
  - cocos2d/cocos2d-x
  - Gamua/Starling-Framework
  - gameplay3d/gameplay
  - jMonkeyEngine/jmonkeyengine
  - SFTtech/openage
  - MonoGame/MonoGame
  - libgdx/libgdx
  - superpowers/superpowers-core
  - AtomicGameEngine/AtomicGameEngine
  - 4ian/GDevelop
  - CRYTEK/CRYENGINE
  - urho3d/urho3d
  - bevyengine/bevy
  - o3de/o3de
  - love2d/love
  - turanszkij/WickedEngine
  - methusalah/OpenRTS
  - phaserjs/phaser
  - melonjs/melonJS
  - BabylonJS/Babylon.js
  - WhitestormJS/whs.js
  - wellcaffeinated/PhysicsJS
  - playcanvas/engine
  - cocos2d/cocos2d-html5
  - craftyjs/Crafty
  - pixijs/pixijs
  - renpy/renpy
  - OpenRA/OpenRA
  - OpenRCT2/OpenRCT2
  - stride3d/stride
  - lance-gg/lance
  - panda3d/panda3d
  - OpenXRay/xray-16
  - korlibs/korge
  - raysan5/raylib
  - amethyst/amethyst
  - orx/orx
  - nCine/nCine
  - cocos/cocos-engine
  - coronalabs/corona
  - hajimehoshi/ebiten
  - hexops/mach
  - HaxeFoundation/haxe
  - HaxeFlixel/flixel
  - Esenthel/EsenthelEngine
  - aws/lumberyard
  - FlaxEngine/FlaxEngine
  - ObEngine/ObEngine
  - KilledByAPixel/LittleJS
  - ppy/osu-framework
  - gosu/gosu
  - PhilMoe/cerberus
  - defold/defold
  - pokepetter/ursina
  - BoomingTech/Piccolo
  - jhasse/jngl
  - pinguin999/ALPACA
  - g3n/engine
  - AmbientRun/Ambient
  - isadorasophia/murder
  - axmolengine/axmol
  - castle-engine/castle-engine
  - flame-engine/flame
  - cubzh/cubzh
  - KinsonDigital/Velaptor
  - crownengine/crown
