id: 10019
name: React Framework
items:
  - vercel/next.js
  - alephjs/aleph.js
  - gatsbyjs/gatsby
  - marmelab/react-admin
  - remix-run/remix
  - remix-run/react-router
  - blitz-js/blitz
  - refinedev/refine
  - Shopify/hydrogen
  - redwoodjs/graphql
  - facebook/docusaurus
