id: 10015
name: Text Editor
items:
  - adobe/brackets
  - limetext/lime
  - textmate/textmate
  - neovim/neovim
  - overleaf/overleaf
  - slap-editor/slap
  - thomaswilburn/Caret
  - Komodo/KomodoEdit
  - leo-editor/leo-editor
  - syl20bnr/spacemacs
  - wsdjeg/SpaceVim
  - alm-tools/alm
  - atom/atom
  - LightTable/LightTable
  - zedapp/zed
  - microsoft/vscode
  - zyedidia/micro
  - neoedmund/neoeedit
  - mawww/kakoune
  - 0x7c13/Notepads
  - onivim/oni2
  - VSCodium/vscodium
  - JetBrains/intellij-community
  - emacs-mirror/emacs
  - rxi/lite
  - lite-xl/lite-xl
  - howl-editor/howl
  - notepad-plus-plus/notepad-plus-plus
  - XhmikosR/notepad2-mod
  - vim/vim
  - Alexey-T/CudaText
  - orbitalquark/textadept
  - apache/netbeans
  - helix-editor/helix
  - zee-editor/zee
  - lapce/lapce
  - focus-editor/focus
  - zed-industries/zed
  - dail8859/NotepadNext
  - cxasm/notepad--
  - rizonesoft/Notepad3
  - zufuliu/notepad4
