id: 10018
name: APM Tool
items:
  - apache/skywalking
  - signoz/signoz
  - dropwizard/metrics
  - pinpoint-apm/pinpoint
  - deepops-io/deepops
  - jaegertracing/jaeger
  - openzipkin/zipkin
  - elastic/apm-server
  - open-telemetry/opentelemetry-collector
  - timescale/promscale
  - graphite-project/graphite-web
  - uptrace/uptrace
  - hyperdxio/hyperdx
