id: 10010
name: Artificial Intelligence
items:
  - nebuly-ai/optimate
  - tensorflow/tensorflow
  - huggingface/transformers
  - opencv/opencv
  - pytorch/pytorch
  - Lightning-AI/pytorch-lightning
  - keras-team/keras
  - scikit-learn/scikit-learn
  - ageitgey/face_recognition
  - BVLC/caffe
  - google-research/bert
  - openai/gym
  - facebookresearch/fastText
  - fastai/fastai
  - ApolloAuto/apollo
  - apache/mxnet
  - open-mmlab/mmdetection
  - PaddlePaddle/Paddle
  - magenta/magenta
  - microsoft/CNTK
  - jina-ai/serve
  - Tencent/ncnn
  - deeplearning4j/deeplearning4j
  - mlflow/mlflow
  - kaldi-asr/kaldi
  - microsoft/nni
  - milvus-io/milvus
  - Theano/Theano
  - tensorlayer/TensorLayer
  - alibaba/MNN
  - Angel-ML/angel
  - XiaoMi/mace
  - towhee-io/towhee
  - SeldonIO/seldon-core
  - SeldonIO/MLServer
  - qdrant/qdrant
