id: 10024
name: Programming Language
items:
  - golang/go
  - swiftlang/swift
  - microsoft/TypeScript
  - rust-lang/rust
  - JetBrains/kotlin
  - python/cpython
  - php/php-src
  - JuliaLang/julia
  - ruby/ruby
  - jashkenas/coffeescript
  - elixir-lang/elixir
  - crystal-lang/crystal
  - PowerShell/PowerShell
  - scala/scala
  - scala/scala3
  - dotnet/roslyn
  - clojure/clojure
  - micropython/micropython
  - erlang/otp
  - nim-lang/Nim
  - AssemblyScript/assemblyscript
  - purescript/purescript
  - elm/compiler
  - dotnet/csharplang
  - red/red
  - ponylang/ponyc
  - Frege/frege
  - goby-lang/goby
  - racket/racket
  - idris-lang/Idris-dev
  - ocaml/ocaml
  - typelead/eta
  - programming-nu/nu
  - gkz/LiveScript
  - IoLanguage/io
  - dlang/dmd
  - terralang/terra
  - dotnet/fsharp
  - rakudo/rakudo
  - chapel-lang/chapel
  - eclipse-archived/golo-lang
  - gosu-lang/gosu-lang
  - ziglang/zig
  - HaxeFoundation/haxe
  - livecode/livecode
  - rocq-prover/rocq
  - vlang/v
  - dart-lang/sdk
  - pharo-project/pharo
  - ring-lang/ring
  - SenegalLang/Senegal
  - objectionary/eo
  - ChavaScript/chavascript
  - beefytech/Beef
  - cue-lang/cue
  - openjdk/jdk
  - nodejs/node
  - bazelbuild/starlark
  - facebook/starlark-rust
  - google/starlark-go
  - winglang/wing
  - diku-dk/futhark
  - flix/flix
  - koka-lang/koka
  - effekt-lang/effekt
  - denoland/deno
  - kcl-lang/kcl
  - wa-lang/wa
  - opentofu/opentofu
