id: 10033
name: Identity Server
items:
  - supertokens/supertokens-core
  - ory/kratos
  - keycloak/keycloak
  - privacyidea/privacyidea
  - apereo/cas
  - casdoor/casdoor
  - DuendeArchive/IdentityServer4
  - nextauthjs/next-auth
  - logto-io/logto
  - zitadel/zitadel
  - lucia-auth/lucia
  - Permify/permify
