id: 10040
name: API tool for developer
items:
  - hoppscotch/hoppscotch
  - boyney123/mockit
  - mockoon/mockoon
  - stoplightio/prism
  - swagger-api/swagger-ui
  - Kong/insomnia
  - Orange-OpenSource/hurl
  - graphql/graphql-playground
  - kamilkisiela/graphql-inspector
  - altair-graphql/altair
  - graphql/graphiql
  - graphql-kit/graphql-voyager
  - graphql-editor/graphql-editor
  - apioo/fusio
  - requestly/requestly
  - keploy/keploy
