id: 10043
name: Go Database
items:
  - hypermodeinc/badger
  - kelindar/column
  - hashicorp/consul
  - peterbourgon/diskv
  - etcd-io/etcd
  - rosedblabs/rosedb
  - lotusdblabs/lotusdb
  - allegro/bigcache
  - boltdb/bolt
  - tidwall/buntdb
  - muesli/cache2go
  - pingcap/tidb
  - tidwall/tile38
  - authzed/spicedb
  - rqlite/rqlite
  - prometheus/prometheus
  - nutsdb/nutsdb
  - ledisdb/ledisdb
  - influxdata/influxdb
  - codenotary/immudb
  - syndtr/goleveldb
  - HDT3213/godis
  - patrickmn/go-cache
  - emitter-io/emitter
  - hypermodeinc/dgraph
  - cockroachdb/cockroach
  - uber/aresdb
  - FerretDB/FerretDB
  - polarsignals/frostdb
  - milvus-io/milvus
