id: 10048
name: UI Framework and UIkit
items:
  - twbs/bootstrap
  - foundation/foundation-sites
  - jgthms/bulma
  - uikit/uikit
  - Semantic-Org/Semantic-UI
  - Dogfalo/materialize
  - pure-css/pure
  - tailwindlabs/tailwindcss
  - elastic/eui
  - ant-design/ant-design
  - mui/material-ui
  - ElemeFE/element
  - milligram/milligram
  - nostalgic-css/NES.css
  - thomaspark/bootswatch
  - saadeghi/daisyui
  - wenzhixin/bootstrap-table
  - kognise/water.css
  - olton/metroui
  - primer/css
  - carbon-design-system/carbon
  - muicss/mui
  - tachyons-css/tachyons
  - vuetifyjs/vuetify
  - themesberg/flowbite
  - ben-rogerson/twin.macro
  - react-bootstrap/react-bootstrap
  - layui/layui
  - vueComponent/ant-design-vue
  - radix-ui/primitives
  - mantinedev/mantine
  - chakra-ui/chakra-ui
  - heroui-inc/heroui
  - microsoft/fast
  - microsoft/fluentui
  - tailwindlabs/headlessui
  - mdbootstrap/TW-Elements
  - adobe/react-spectrum
  - GeekyAnts/NativeBase
  - segmentio/evergreen
  - tusen-ai/naive-ui
  - uber/baseweb
  - element-plus/element-plus
  - sailboatui/sailboatui
  - shadcn-ui/ui
  - tamagui/tamagui
