id: 10050
name: Open Source Forum Software
items:
  - forem/forem
  - discourse/discourse
  - NodeBB/NodeBB
  - flarum/flarum
  - debiki/talkyard
  - phpbb/phpbb
  - fluxbb/fluxbb
  - LemmyNet/lemmy
  - apache/answer
