id: 10051
name: Security Tool
items:
  - turbot/steampipe
  - prowler-cloud/prowler
  - aquasecurity/trivy
  - CISOfy/lynis
  - future-architect/vuls
  - aquasecurity/tfsec
  - quay/clair
  - anchore/syft
  - infobyte/faraday
  - gitleaks/gitleaks
  - kubescape/kubescape
  - aquasecurity/starboard
  - aquasecurity/kube-bench
  - anshumanbh/git-all-secrets
  - aquasecurity/kube-hunter
  - bridgecrewio/checkov
  - Lissy93/personal-security-checklist
  - smicallef/spiderfoot
  - secdev/scapy
  - RustScan/RustScan
  - presidentbeef/brakeman
  - securego/gosec
  - urbanadventurer/WhatWeb
  - tenable/terrascan
  - lunasec-io/lunasec
  - openclarity/kubeclarity
  - anchore/grype
  - jumpserver/jumpserver
  - projectdiscovery/nuclei
  - zaproxy/zaproxy
  - anantshri/svn-extractor
  - adrecon/ADRecon
  - adrecon/AzureADRecon
  - s4n7h0/Halcyon-IDE
  - DataSploit/datasploit
  - nmap/nmap
  - wazuh/wazuh
  - rapid7/metasploit-framework
  - deepfence/ThreatMapper
  - desaster/kippo
  - aboul3la/Sublist3r
  - gamelinux/passivedns
  - lanmaster53/recon-ng
  - jeremylong/DependencyCheck
  - tenzir/tenzir
  - matanolabs/matano
  - chipsec/chipsec
  - kyverno/kyverno
  - cloudquery/cloudquery
  - slimtoolkit/slim
  - akto-api-security/akto
  - deepfence/SecretScanner
  - deepfence/PacketStreamer
  - intuitem/ciso-assistant-community
