id: 10063
name: Kubernetes Tooling
items:
  - kubernetes/minikube
  - rancher-sandbox/rancher-desktop
  - kubernetes-sigs/kind
  - k3s-io/k3s
  - prometheus-operator/prometheus-operator
  - kubescape/kubescape
  - portainer/portainer
  - helm/helm
  - rancher/rancher
  - robusta-dev/robusta
  - komodorio/validkube
  - ReallyLiri/kubescout
  - abahmed/kwatch
  - kubeshop/botkube
  - pixie-io/pixie
  - ContainerSolutions/helm-monitor
  - odigos-io/odigos
  - lensapp/lens
  - kyverno/kyverno
  - opencost/opencost
  - kubeshop/monokle
  - komodorio/helm-dashboard
  - projectcapsule/capsule
  - bridgecrewio/checkov
  - kubeshark/kubeshark
  - robusta-dev/kubernetes-chatgpt-bot
  - robusta-dev/krr
  - kubernetes-sigs/kwok
  - gimlet-io/gimlet
  - berops/claudie
  - gimlet-io/capacitor
  - loft-sh/vcluster
  - meshery/meshery
