id: 10078
name: ChatGPT Apps
items:
  - arc53/DocsGPT
  - chenfei-wu/TaskMatrix
  - AutumnWhj/ChatGPT-wechat-bot
  - wong2/chatgpt-google-extension
  - ourongxing/chatgpt-vercel
  - openai-translator/openai-translator
  - pingcap/ossinsight
  - lencx/ChatGPT
  - Chanzhaoyu/chatgpt-web
  - fuergaosi233/wechat-chatgpt
  - zhayujie/chatgpt-on-wechat
  - anse-app/chatgpt-demo
  - vincelwt/chatgpt-mac
  - kaixindelele/ChatPaper
  - mckaywrigley/chatbot-ui
  - openai-translator/bob-plugin-openai-translator
  - mpociot/chatgpt-vscode
  - josStorer/chatGPTBox
  - m1guelpf/chatgpt-telegram
  - gragland/chatgpt-chrome-extension
  - madawei2699/myGPTReader
  - yihong0618/xiaogpt
  - ConnectAI-E/feishu-openai
  - Yue-Yang/ChatGPT-Siri
  - Bin-Huang/chatbox
  - chatpire/chatgpt-web-share
  - ChatGPTNextWeb/NextChat
  - 202252197/ChatGPT_JCM
  - lss233/kirara-ai
  - sqlchat/sqlchat
  - Significant-Gravitas/AutoGPT
  - reworkd/AgentGPT
  - Vision-CAIR/MiniGPT-4
  - yoheinakajima/babyagi
  - nat/openplayground
  - mlc-ai/web-llm
  - langflow-ai/langflow
