id: 10083
name: Programming Language of China
items:
  - aliyun/darabonba
  - AnonymousAAArdvark/qi
  - aya-prover/aya-dev
  - baixing/jedi
  - calcit-lang/calcit
  - cicada-lang/cicada
  - cinogama/woolang
  - covscript/covscript
  - daokoder/dao
  - deeplang-org/deeplang
  - fanx-dev/fanx
  - goplus/xgo
  - HVML/PurC
  - chuangzaojun/karl
  - kcl-lang/kcl
  - linuxdeepin/unilang
  - nature-lang/nature
  - ProjectDimlight/RuCalculus
  - StepfenShawn/Cantonese
  - tu-lang/tu
  - wa-lang/wa
  - wenyan-lang/wenyan
  - XtherDevTeam/reXscript
  - yuyan-lang/yuyan
