id: 10097
name: AI Training Observability
items:
  - anthropics/claude-code
  - openai/codex
  - Aider-AI/aider
  - block/goose
  - antinomyhq/forge
  - plandex-ai/plandex  
  - All-Hands-AI/OpenHands
  - AutoCodeRoverSG/auto-code-rover
  - sourcegraph/cody
  - qodo-ai/pr-agent
  - vanna-ai/vanna
