id: 10098
name: Model Context Protocol (MCP) Client
items:
  - hyperbrowserai/HyperAgent
  - jiasyuanchu/mcp-chat-bot
  - ggozad/oterm
  - sakil786/airbnb_mcp
  - nbonamy/witsy
  - shaoyingchen/mcp-client-llm
  - tarasyarema/prodex-js
  - study944/ai-agent-zxc
  - chrishayuk/mcp-cli
  - platinum-hill/cobolt
  - settledco/mcp-for-laravel
  - dictybase-docker/mcphost
  - rggh/mcp-python-client
  - sedong-choi/unity-mcp-typescript
  - cognitivecomputations/dolphin-mcp
  - annali/historiq
  - regibyte/mcp-client-app
  - groq/groq-desktop-beta
  - c1pher-cn/ha-xiaozhi-mcp
  - mario-andreschak/flujo
  - lingster/mcp-llm
  - akktrsst/mcp_agent_airbnb
  - gnosis23/tiny-mcp-client
  - jagan-shanmugam/mattermost-mcp-host
  - thinkinaixyz/deepchat
  - swairshah/claude-cli-mcp-client
  - jiaminghuanghjm/zsh_chatbot_mcp
  - nerding-io/n8n-nodes-mcp
  - truffle-ai/saiki
  - getcursor/cursor
  - 3choff/mcp-chatbot
  - continuedev/continue
  - milind-soni/mcp
  - aswincandra/fast-mcp-client
  - coldielb/blnk
  - larkooo/dojo-mcp
  - evilsocket/nerve
  - evanzhoudev/raycast-mcp
  - jobsonlook/xhs-mcp
  - justjoehere/mcp_gradio_client
  - hjlarry/dify-plugin-mcp_agent
  - openagentplatform/dive-mcp-host
  - bigsweetpotatostudio/hyper-mcp-terminal
  - mshojaei77/easymcp
  - acnet-ai/omnitaskagent
  - dannyroosevelt/pipedream-mcp-ui
  - supercorp-ai/superinterface
  - bytedance/ui-tars-desktop
  - ravitemer/mcphub.nvim
  - wimpywarlord/mcp-react-dev-tools
  - mdhelaluddinbiswas/open-mcp-client
  - pathintegral-institute/mcpm.sh
  - binarybana/easyrag
  - arenoth/mcp-agent
  - junjiem/dify-plugin-agent-mcp_sse
  - blacsheep/llm-amap-mcp
  - lizqwerscott/mcp.el
  - alessandrodorazio/mcp-client-server
  - saqadri/mcp_agent_streamlit_rag
  - HEAD/foafrtc
  - pawankumar94/jira_mcp_streamlit
  - omchillure/mcpui
  - fbeunder/mcp_flask
  - box-community/box-mcp-pydantic-ai
  - navneet-ag/cursor-jira-mcp
  - hideya/mcp-client-langchain-ts
  - dicklesworthstone/ultimate_mcp_client
  - copilotkit/open-mcp-client
  - teamsparkai/teamspark-workbench
  - itisaevalex/mistr-agent
  - zinja-coder/zin-mcp-client
  - paulrobello/mcp_langgraph_tools
  - swairshah/term-mcp-client
  - kamrul1157024/mcp-client
  - kokoiruby/kopilot-mcp
  - netixc/speech-mcp
  - langchain-ai/langchainjs-mcp-adapters
  - Xingsandesu/CarrotAI
  - zeeshanunique/mcp-client
  - zed-industries/zed
  - Lucassssss/eechat
  - cloudwalk/hermes-mcp
  - yoheimuta/protolint
  - slavashvets/mcp-http-client-example
  - machaojin1917939763/mcp-ui
  - roocodeinc/roo-code
  - danny-avila/LibreChat
  - yashmakan/flutter_mcp
  - anycontext-ai/remote-mcp-chat
  - gongrzhe/open-mcp-client
  - albertvillanova/tinyagents
  - deco-sites/vertex-mcp-3
  - maurostyleman/kafrma-backend
  - shren207/weather-mcp
  - nick1udwig/kibitz
  - lastmile-ai/mcp-agent
  - hicodermonkey/agents-mcp-cloud
  - zovi343/oai_mcp_code_agent
  - tony-nexartis/anthropic_mcp_hackathon_sse_client
  - michaelmoriarty67/mcp-autogen
  - rosiefaulkner/langgraph-voice-agent
  - fkesheh/mcp-ai-agent
  - nimishchaudhari/openhands-resolver-mcp
  - Chainlit/chainlit
  - fbeunder/mcp_cli_client
  - leartbeqiraj1/openai-mcp-client
  - daodao97/chatmcp
  - apify/tester-mcp-client
  - qu3ai/qu3-app
  - mashriram/mcp_client_local
  - BigSweetPotatoStudio/HyperChat
  - ateeyak/n8n-nodes-mcp
  - viktormarinho/mcpeste
  - AdamStrojek/rust-agentai
  - mizakahk/mcp-gomamayo
  - destiner/oneshot
  - keli-wen/mcp_chatbot
  - daydreamsai/daydreams
  - scriptoshi/laravel-mcp-client
  - buyitsydney/codingbaby-browser-mcp
  - evalstate/fast-agent
  - jeomon/mcp-agent
  - copilotkit/mcp-client
  - seekrays/seekchat
  - rectalogic/pydantic-mcp
  - microsoft/genaiscript
  - astrabert/tysva
  - shwstone/mcp-oi-wiki
  - sooperset/mcp-client-slackbot
  - gulp-ai/osmosis-mcp-4b-demo
  - ThinkInAIXYZ/deepchat
  - tuannvm/slack-mcp-client
  - jlmelis/mcp-proving-ground-client
  - shaharia-lab/mcp-frontend
  - alishangtian/proteus-ai
  - ChatGPTNextWeb/NextChat
  - edanyal/mcp-client
  - michaeldslim/mcp-notion-api
  - nanbingxyz/5ire
  - NitroRCr/AIaW
  - supermemoryai/install-mcp
  - cgoinglove/mcp-client-chatbot
  - abiorh001/mcp_omni_connect
  - extopico/llama-server_mcp_proxy
  - debedb/mcp-aws
  - fabriborgobello/chat-mcp-rag
  - github.com/Enconvo
  - rakesh-eltropy/mcp-client
  - aranyak-4002/figma-design-mcp
  - mctrinh/mcp-chatbot
  - mihirrd/ollama-mcp-client
  - duke7able/gemini-mcp-desktop-client
  - craigsdennis/openai-responses-mcp-client-enabled
  - purunep/streamble-http-mcp-client
  - twwch/mcp-feishu-bot
  - fernandezpablo85/mcpiol
  - xingsandesu/carrotai
  - rosaboyle/mcp-playground
  - difybase/dify-connect-mcp
  - rairai77/weather-tool-with-mcp
  - cloud-thinker-ai/mcp-manager
  - emredeveloper/mcp-turkey-weather
  - vincent-pli/mcp-cli-host
  - NVIDIA/AIQToolkit
  - ellieli0630/langgraph-mcp-agent-twitter
  - openagentplatform/dive
  - rggh/refactored-octo-parakeet
  - cherryhq/cherry-studio
  - rooseveltadvisors/fastapi-mcp-client
  - kabrony/claude-agent-mcp
  - tkellogg/tupac
  - justinhuang0208/launchbar-mcp_agent
  - ai-ql/chat-mcp
  - hazyresearch/minions
  - polymath-raval/mcp_example
  - chainlit/chainlit
  - hideya/mcp-client-langchain-py
  - bigsweetpotatostudio/hyperchat
  - byeblack/wasi_mcp_client
  - chunkydotdev/bldbl-mcp
  - jinruoxinchen/mcp-web-client
  - l145dev/google-maps-mcp-speech
  - juspay/bedrock-mcp-connector
  - geli2001/mcp-terminal
  - tim-schultz/mcp-client-rs
  - yeakub108/mcp-client
  - nullplatform/np-mcp-controlplane-proxy
  - crayon3shawn/mcp-cli-manager
  - taggartbg/vibeframe
  - adafap/api-mcp
  - shane-kercheval/mcp-client-agent
  - setkyar/claude-mcp
  - kartikeyapandey20/mcp-client
  - mediar-ai/mcp-server-client-computer-use-ai-sdk
  - sidharthrajaram/mcp-sse
  - luohy15/y-cli
  - obrr-hhx/askanything
  - thingspanel/thingspanel-mcp
  - pietrozullo/mcp-use
  - compiler-inc/swiftmcp
  - wrediam/n8n-coolify-mcp-tools
  - xkzy/vscode-mcp-rag
  - robert-githubusername/winformsapp-mcp
  - toolbase-ai/toolbase
  - jodobear/sparcaroo
  - nachoal/react-agent-with-mcp
  - hideya/langchain-mcp-tools-ts-usage
  - kamath/chat
  - williamvd4/mcp-client-cli
  - s-k-srivastava/mcp-math-solver
  - shuakami/mcp-download
  - packetnomad/cursor-apple-notes-indexer
  - Ejb503/multimodal-mcp-client
  - kicker315/deepseek_qgis_mcp
  - cpage-pivotal/cf-mcp-client
  - xark-argo/argo
  - packages/mcp-client
  - terminallylazy/mcp-on-fhir
  - HEAD/mcp_clients
  - kin-10/mcp_llm
  - danieloh30/quarkus-agentic-mcp
  - HEAD/mcp_simple_slackbot
  - nicozumarraga/light-mcp-agents
  - mario-andreschak/FLUJO
  - imnmv/clauder
  - bigmb/mb_mcp
  - utkucy/arbitrum-mcp-tools
  - georgi-terziyski/mcp_client_ollama
  - i2y/langchaingo-mcp-adapter
  - lstm-kirigaya/openmcp-client
  - ananis25/mcp-client-ref
  - huggingface/smolagents
  - mastra-ai/discord-mcp-bot
  - umuo/hot-topic-mcp
  - firebase/genkit
  - namank5x/kiters-mcp-client
  - block/goose
  - mark3labs/mcphost
  - dshivendra/crewai_mcp_adapter
  - faraazahmad/mcp_debug
  - adamdude828/claude-mcp-agent
  - ejb503/multimodal-mcp-client
  - nikunj2003/llama-mcp-streamlit
  - techspawn/turbo-mcp-client
  - amidabuddha/console-chat-gpt
  - microsoft/vscode
  - xprilion/genkit-mcp-client-blender
  - matthewhand/open-swarm
  - toberyan/deepin-mcp
  - aasherkamal216/axiom
  - gh05tcrew/pentestmcp
  - pickpppcc/qbittorrent-mcp
  - mcp-use/mcp-use
  - gptme/gptme
  - m-mcp/web-search
  - lalanikarim/langgraph-mcp-pipeline
  - runebookai/tome
  - mindpal-ai/mindpal
  - sparktsao/mcp_meet_agentiq
  - dory-ai/n8n-mcp-bridge
  - ezyang/codemcp
  - vikashloomba/copilot-mcp
  - russellluo/cmcp
  - denizakansoy/mcphack
  - aws-samples/sample-nova-sonic-mcp
  - evolutionapi/evo-ai
  - csonigo/slack-mcp-client
  - runekaagaard/aterm2
  - aws/amazon-q-developer-cli
  - cam10001110101/anthropic-mcp-connector
  - john-lin/agentic-slackbot
  - karthikv2k/chat-mcp
  - minyang-chen/seat-booking-agent
  - k3d3/firefox_mcpbridge
  - kirintea/mcp_modularity
  - gcc3/simple-ai-chat
  - autometa-dev/whatsapp-mcp-voice-agent
  - intelligent-systems-lab/mcp_client_ollama
  - ibelick/zola
  - zaidmukaddam/scira-mcp-chat
  - down-to-earth1994/auto-mcp-client
  - wxhzhwxhzh/drssionpagemcp
  - wintertechforum/mcp-demo
  - jmand626/473-mcpproject
  - CherryHQ/cherry-studio
  - cline/cline
  - heminoid/mcp-voice-agent
  - richardanaya/utilitybelt
  - leehack/flutter-mcp-ai-chat
  - korchasa/speelka-agent
  - garvk/mcp-postgresql-agent-hack
  - maitreyam/clap-agents
  - kuzushilabsorg/mcp-clients
  - kkul-eng/mcp-claude-demo
  - Abiorh001/mcp_omni_connect
  - adhikasp/mcp-client-cli
  - keta1930/mcp-agent-graph
  - danny-avila/librechat
  - shahshrey/universal-mcp-ui
  - VikashLoomba/copilot-mcp
  - funwarioisii/sample-mcp-rails
  - bro-in-law/mcp-demo-frontend
  - opensumi/core
  - sansan4ez/mcp-cli
  - shawn996/mcp_ha_xiaozhi
  - wong2/mcp-cli
  - yonaka15/mcp-client-demo
  - rusiaaman/chat.md
