id: 10107
name: Vibe Coding Tools
items:
  - stackblitz/bolt.new
  - dyad-sh/dyad
  - cloudflare/vibesdk
  - srcbookdev/srcbook
  - get-convex/chef
  - Pythagora-io/pythagora
  - wandb/openui
  - Pythagora-io/gpt-pilot
  - mckaywrigley/chatbot-ui
  - BuilderIO/ai-shell
  - e2b-dev/E2B
  - codestoryai/aide
  - toeverything/AFFiNE
  - we0-dev/we0
  - giselles-ai/giselle
