id: 10102
name: Documentation Generator
items:
  - fuma-nama/fumadocs
  - facebook/docusaurus
  - mkdocs/mkdocs
  - squidfunk/mkdocs-material
  - sphinx-doc/sphinx
  - vuejs/vuepress
  - vuejs/vitepress
  - 11ty/eleventy
  - hexojs/hexo
  - getzola/zola
  - HugoBlox/hugo-blox-builder
  - docsifyjs/docsify
  - GitbookIO/gitbook
  - readthedocs/readthedocs.org
  - just-the-docs/just-the-docs
  - google/docsy
  - alex-shpak/hugo-book
  - matcornic/hugo-theme-learn
  - jpedroschmitz/rocketdocs
  - shuding/nextra
  - rust-lang/mdBook
  - doxygen/doxygen
  - antora/antora
