id: 10105
name: llm-gateways
items:
  - 8monkey-ai/hebo-gateway
  - APIParkLab/APIPark
  - BerriAI/litellm
  - bestruirui/octopus
  - casdoor/casdoor
  - cloud-apim/otoroshi-llm-extension
  - coaidev/coai
  - fabiojbg/LLMApiGateway
  - getaxonflow/axonflow
  - hypersigilhq/hypersigil
  - jasonkuperberg/ai-gateway-resources
  - katanemo/plano
  - KikuAI-Lab/reliapi
  - Kong/kong
  - langfuse/oss-llmops-stack
  - LianjiaTech/bella-openapi
  - maximhq/bifrost
  - Nayjest/lm-proxy
  - nghyane/llm-mux
  - ongoingai/gateway
  - ozanunal0/Prometheus-Gateway
  - Portkey-AI/gateway
  - r9s-ai/open-next-router
  - shengyanli1982/llmproxy
  - starbaser/ccproxy
  - sxueck/llm-gateway
  - teilomillet/hapax
  - theopenco/llmgateway
  - vllora/vllora
  - wa91h/local-ai-toolkit
