id: 10104
name: ai-gateways
items:
  - 1mcp-app/agent
  - 8monkey-ai/hebo-gateway
  - 82ch/MCP-Dandan
  - aarora79/mcp-gateway
  - agentgateway/agentgateway
  - agentic-community/mcp-gateway-registry
  - alibaba/higress
  - AmoyLab/Unla
  - APIParkLab/APIPark
  - ArcadeAI/arcade-mcp
  - archestra-ai/archestra
  - atinux/atidraw
  - atopos31/llmio
  - BerriAI/litellm
  - bestruirui/octopus
  - casdoor/casdoor
  - cloud-apim/otoroshi-llm-extension
  - coaidev/coai
  - codingjam/bridge-mcp
  - COO-LLM/coo-llm-main
  - director-run/director
  - dunialabs/peta-core
  - e2b-dev/awesome-mcp-gateways
  - envoyproxy/ai-gateway
  - fabiojbg/LLMApiGateway
  - fiddlecube/compliant-llm
  - getaxonflow/axonflow
  - hypersigilhq/hypersigil
  - hyprmcp/jetski
  - hyprmcp/mcp-gateway
  - jasonkuperberg/ai-gateway-resources
  - kaitranntt/ccs
  - katanemo/plano
  - KenisLabs/arka-mcp-gateway
  - Kenza-AI/sagify
  - KikuAI-Lab/reliapi
  - Kong/kong
  - krakend/krakend-ce
  - langfuse/oss-llmops-stack
  - LianjiaTech/bella-openapi
  - maximhq/bifrost
  - mcp-use/mcp-use
  - mcpjungle/MCPJungle
  - metatool-ai/metamcp
  - MigoXLab/LMeterX
  - nautilus-ops/mcp-center
  - Nayjest/lm-proxy
  - nextlevelbuilder/goclaw
  - nghyane/llm-mux
  - octelium/octelium
  - ongoingai/gateway
  - openguardrails/openguardrails
  - ozanunal0/Prometheus-Gateway
  - Portkey-AI/gateway
  - postrv/forgemax
  - QuantumNous/new-api
  - r9s-ai/open-next-router
  - riipandi/sorai
  - samanhappy/mcphub
  - shengyanli1982/llmproxy
  - stacklok/codegate
  - starbaser/ccproxy
  - sxueck/llm-gateway
  - teilomillet/hapax
  - TheLunarCompany/lunar
  - theopenco/llmgateway
  - TPIsoftwareOSPO/digiRunner-Open-Source
  - vllm-project/semantic-router
  - vllora/vllora
  - w3z4y4/mcp-gateway
  - wa91h/local-ai-toolkit
