id: 10115
name: LLM Gateway & Proxy
items:
  - BerriAI/litellm
  - Portkey-AI/gateway
  - Helicone/helicone
  - lm-sys/FastChat
  - openai/openai-python
  - bentoml/OpenLLM
  - Kong/kong
  - chatchat-space/Langchain-Chatchat
  - open-webui/open-webui
  - coaidev/coai
