id: 10127
name: AI Governance
items:
  - fairlearn/fairlearn
  - Trusted-AI/AIF360
  - Trusted-AI/AIX360
  - microsoft/responsible-ai-toolbox
  - shap/shap
  - meta-pytorch/captum
  - PAIR-code/what-if-tool
  - microsoft/presidio
  - guardrails-ai/guardrails
  - EthicalML/xai
