id: 10131
name: Synthetic Data
items:
  - sdv-dev/SDV
  - gretelai/gretel-synthetics
  - mostly-ai/mostlyai
  - Kiln-AI/Kiln
  - ServiceNow/SyGra
  - NVIDIA/synthda
  - Clearbox-AI/clearbox-synthetic-kit
  - starfishdata/starfish
  - TonicAI/tonic_validate
