id: 10135
name: AI Observability
items:
  - langfuse/langfuse
  - mlflow/mlflow
  - Arize-ai/phoenix
  - evidentlyai/evidently
  - traceloop/openllmetry
  - Helicone/helicone
  - openlit/openlit
  - AgentOps-AI/agentops
  - pydantic/logfire
  - uptrain-ai/uptrain
  - whylabs/whylogs
  - zenml-io/zenml
