id: 10139
name: A2A Protocol
items:
  - a2aproject/A2A
  - google/adk-python
  - google/adk-java
  - agent-network-protocol/AgentNetworkProtocol
  - themanojdesai/python-a2a
  - Coral-Protocol/Anemoi
  - neuroglia-io/a2a-net
  - cpp-agan-team/a2a-cpp-sdk
  - RubensZimbres/Multi-Agent-System-A2A-ADK-MCP
  - isekOS/awesome-a2a-agents
