name: Verify API server

on:
  pull_request:
    paths:
      - 'src/services/api-server/**'

defaults:
  run:
    shell: bash
    working-directory: src/services/api-server

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        working-directory: .
        run: npm install

      - name: Build OSSInsight Types Dependencies
        working-directory: .
        run: npm run build -w @ossinsight/types

      - name: Verify Sources
        run: npm run test

      - name: Build Project
        run: npm run build:ts
