/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'about',
      label: 'About',
      customProps: {
        hide_title: true,
        description: 'OSS Insight is a powerful insight tool that can help you analyze any GitHub repository or developer. And you can get insights with the monthly and historical rankings as well.',
      }
    },
    {
      type: 'category',
      label: 'Workshop',
      items: [{ type: 'autogenerated', dirName: 'workshop' }],
      customProps: {
        collapsed: true
      }
    },
    {
      type: 'category',
      label: 'API',
      // @ts-ignore
      items: [
        ...require('./docs/api/sidebar.js'),
        {
          type: 'doc',
          id: 'api/showcase',
          label: 'Showcase',
          customProps: {
            description: 'OSS Insight API Showcase',
          }
        },
      ],
      customProps: {
        collapsed: false
      }
    },
    {
      type: 'doc',
      id: 'faq',
      label: 'FAQ',
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
